services:
  windrose:
    image: ghcr.io/mrguato/windrose-dedicated-server:latest
    # build: .
    container_name: windrose
    hostname: windrose
    restart: unless-stopped
    stop_grace_period: 90s
    network_mode: host
    env_file:
      - .env
    environment:
      WINDROSE_APP_ID: 4129620
      DISPLAY: ":99"
      WINEDEBUG: "-all"
    volumes:
      - ./data:/data
      - ./steam-home:/home/steam
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:rw,nosuid,nodev,size=128m
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'WindroseServer-Win64-Shipping.exe' >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5m
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    # deploy:
    #   resources:
    #     limits:
    #       memory: 12G
    #       cpus: "4.0"
